/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Month = IDL.Nat;
export const Coach = IDL.Record({
  'center' : IDL.Text,
  'name' : IDL.Text,
  'salaries' : IDL.Float64,
});
export const MonthlyDashboard = IDL.Record({
  'month' : Month,
  'revenue' : IDL.Float64,
  'centerName' : IDL.Text,
  'year' : IDL.Nat,
  'target' : IDL.Float64,
  'coaches' : IDL.Vec(Coach),
});

export const idlService = IDL.Service({
  'deleteDashboard' : IDL.Func([IDL.Nat], [], []),
  'getAllDashboards' : IDL.Func([], [IDL.Vec(MonthlyDashboard)], ['query']),
  'getDashboard' : IDL.Func([IDL.Nat], [MonthlyDashboard], ['query']),
  'getDashboardsByYear' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MonthlyDashboard)],
      ['query'],
    ),
  'upsertDashboard' : IDL.Func([IDL.Nat, MonthlyDashboard], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Month = IDL.Nat;
  const Coach = IDL.Record({
    'center' : IDL.Text,
    'name' : IDL.Text,
    'salaries' : IDL.Float64,
  });
  const MonthlyDashboard = IDL.Record({
    'month' : Month,
    'revenue' : IDL.Float64,
    'centerName' : IDL.Text,
    'year' : IDL.Nat,
    'target' : IDL.Float64,
    'coaches' : IDL.Vec(Coach),
  });
  
  return IDL.Service({
    'deleteDashboard' : IDL.Func([IDL.Nat], [], []),
    'getAllDashboards' : IDL.Func([], [IDL.Vec(MonthlyDashboard)], ['query']),
    'getDashboard' : IDL.Func([IDL.Nat], [MonthlyDashboard], ['query']),
    'getDashboardsByYear' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MonthlyDashboard)],
        ['query'],
      ),
    'upsertDashboard' : IDL.Func([IDL.Nat, MonthlyDashboard], [], []),
  });
};

export const init = ({ IDL }) => { return []; };