/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Coach {
  'center' : string,
  'name' : string,
  'salaries' : number,
}
export type Month = bigint;
export interface MonthlyDashboard {
  'month' : Month,
  'revenue' : number,
  'centerName' : string,
  'year' : bigint,
  'target' : number,
  'coaches' : Array<Coach>,
}
export interface _SERVICE {
  'deleteDashboard' : ActorMethod<[bigint], undefined>,
  'getAllDashboards' : ActorMethod<[], Array<MonthlyDashboard>>,
  'getDashboard' : ActorMethod<[bigint], MonthlyDashboard>,
  'getDashboardsByYear' : ActorMethod<[bigint], Array<MonthlyDashboard>>,
  'upsertDashboard' : ActorMethod<[bigint, MonthlyDashboard], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];